export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const CLIENT_MENU = 'CLIENT_MENU';
export const APPBAR_MENU_BUTTON = 'APPBAR_MENU_BUTTON';
export const APPBAR_ACTION = 'APPBAR_ACTION';


export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

/**
 * Page
 */
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';

/**
 * Service Actions
 */
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const LOAD_SERVICE_SUCCESS = 'LOAD_SERVICE_SUCCESS';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
